# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170224_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='/products/img/'),
        ),
    ]
