# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170224_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='products/img'),
        ),
    ]
